// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdsvtpvdeknofknhzgdv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkc3Z0cHZkZWtub2Zrbmh6Z2R2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MTc5NzIsImV4cCI6MjA2NjM5Mzk3Mn0.CLFRjmxAYhj3gLgh7ZeanIku3V5J4XlVlp5gugjbXZc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});